<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Buffer.fs" />
    <Compile Include="AmqpTypes.fs" />
    <Compile Include="Amqp.fs" />
    <Compile Include="Agent.fs" />
    <Compile Include="AgentMessages.fs" />
    <Compile Include="TcpConnectionAgent.fs" />
    <Compile Include="AmqpConnectionAgent.fs" />
    <Compile Include="HandshakeAgent.fs" />
    <Compile Include="HeartbeatAgent.fs" />
    <Compile Include="ConnectionSupervisor.fs" />
    <Compile Include="ChannelAgent.fs" />
    <Compile Include="AmqpClient.fs" />
  </ItemGroup>
</Project>